### ISSUE TITLE
Trouble on visualisation of /aruco_markers and /aruco_poses topics on RVIZ2

### ISSUE THREAD

**Issue by ghost** [JMU-ROBOTICS-VIVA/ros2_aruco#4]
Hey,
I am using ROS2 Foxy and Nvidia AGX Orin, and I found out that this ros2_aruco repo is one of the reliable repo for usage of Stereo ZED 2 camera. While I was executing `ros2 launch zed_display_rviz2 display_zed2.launch.py` and `ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/zed2/zed_node/left_raw/image_raw_color -p camera_info_topic:=/zed2/zed_node/left_raw/camera_info` on separated terminals, I found out that camera can read data from aruco markers(Confirmed using  `ros2 topic echo /aruco_markers`, `ros2 topic echo /aruco_poses` ) but they are not visualised on RVIZ. Does anyone know what's the problem? Also, I've tested topics for case of `ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/aruco_markers -p camera_info_topic:=/aruco_poses` but same unpleasant result. Thanks.

**Comment by jkaniuka** [comment]
@segapss Hi, in order for marker positions to be visible in RViz you must first add them. In RViz, in the lower left corner, click **Add** and then go to the **By topic** tab. There you will find topics with AR marker positions. Select the appropriate topic and click OK. 

To run the AR marker detection node, use the command  `ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/zed2/zed_node/left_raw/image_raw_color -p camera_info_topic:=/zed2/zed_node/left_raw/camera_info`

The `ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/aruco_markers -p camera_info_topic:=/aruco_poses` command is incorrect.

**Comment by ghost** [comment]
@jkaniuka  Thanks for the reply. Many people has told me about **Add** section before, so I tried it also. But when I was tried to select **PoseArray**, it still cannot detect markers. And I am not quite sure which topics are highly relevant on AR marker positions. Could you clarify more for the characteristics or selection of topics for that? And for `ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/aruco_markers -p camera_info_topic:=/aruco_poses`, which point is incorrect on this command? I want to get knowledge for it after correcting the error. Thanks.
<img width="386" alt="screenshot" src="https://user-images.githubusercontent.com/67156230/233488346-54cbcdf6-f1ff-49b6-8260-9fb228cd99f9.png">
<img width="362" alt="screenshot2" src="https://user-images.githubusercontent.com/67156230/233488363-b1f42cc8-5c2e-43d8-8db0-1d47cc33babc.png">

**Comment by jkaniuka** [comment]
@segapss 

> But when I was tried to select PoseArray, it still cannot detect markers. 

On the first screenshot, I see that you managed to add the display of **PoseStamped** messages published on `/aruco_poses` topic. You can change the Shape from Arrow to Axes for convenience.

> And I am not quite sure which topics are highly relevant on AR marker positions. Could you clarify more for the characteristics or selection of topics for that? 

You can find this information in [**README.md**](https://github.com/JMU-ROBOTICS-VIVA/ros2_aruco/blob/main/README.md) (Subscriptions & Published Topics).
![image](https://user-images.githubusercontent.com/80155305/233792132-4e593a1f-4cf0-43c4-9378-daaa9a2f05b8.png)

> And for ros2 run ros2_aruco aruco_node --ros-args -p image_topic:=/aruco_markers -p camera_info_topic:=/aruco_poses, which point is incorrect on this command?

**image_topic** and **camera_info_topic** are parameters, which are also described in the [**README.md**](https://github.com/JMU-ROBOTICS-VIVA/ros2_aruco/blob/main/README.md) (Parameters).
![image](https://user-images.githubusercontent.com/80155305/233792302-48e96c39-c43f-4df9-8d97-26a40d66921e.png)

Node **aruco_node** subscribes to topics given as `image_topic` and `camera_info_topic` parameters and publishes on topics `/aruco_poses` and `/aruco_markers`. 

Hope I helped :+1:

**Comment by ghost** [comment]
@jkaniuka  Solved. I forgot to clone other's repository who has worked on same repo of ros2_aruco. Because I cloned original repo on here, but didn't know he/she was collaborating some works on their space. But thanks for your assistance also!
